name=police_car_library
version=1.0.0
author=Jeremy Hung
maintainer=Jeremy Hung
sentence=Timer example
paragraph= Timer example
category=Timing
url=https://google.com
architectures=avr
includes=police_car_library.h